### ISSUE TITLE
Load error on cloud version of YouTrack

### ISSUE THREAD

**Issue by pmalouin** [pbauerochse/youtrack-worklog-viewer#18]
When setting up the connection with the hosted/cloud version of YouTrack (myjetbrains.com), I get the following error at the bottom of the window:

`Could not get categories for groupBy criterias from YouTrack (Message: Not Found, StatusCode: 404).`

Here is the entry in the log file:
```
java.lang.IllegalStateException: Could not get categories for groupBy criterias from YouTrack (Message: Not Found, StatusCode: 404)
	at de.pbauerochse.worklogviewer.util.ExceptionUtil.getIllegalStateException(ExceptionUtil.java:34) ~[youtrack-worklog-viewer-2.2.2.jar:na]
	at de.pbauerochse.worklogviewer.util.ExceptionUtil.getIllegalStateException(ExceptionUtil.java:30) ~[youtrack-worklog-viewer-2.2.2.jar:na]
	at de.pbauerochse.worklogviewer.youtrack.connector.YouTrackConnectorBase.getPossibleGroupByCategories(YouTrackConnectorBase.java:73) ~[youtrack-worklog-viewer-2.2.2.jar:na]
	at de.pbauerochse.worklogviewer.fx.tasks.GetGroupByCategoriesTask.call(GetGroupByCategoriesTask.java:27) ~[youtrack-worklog-viewer-2.2.2.jar:na]
	at de.pbauerochse.worklogviewer.fx.tasks.GetGroupByCategoriesTask.call(GetGroupByCategoriesTask.java:14) ~[youtrack-worklog-viewer-2.2.2.jar:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_101]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_101]
```

The version of YouTrack is:
> YouTrack 6.5
> Build 17122 19-Jul-2016 21:22

**Comment by pmalouin** [comment]
While fiddling manually with the API, I was able to fix this issue by appending `/youtrack` at the end of the YouTrack-URL:
Instead of `https://xxx.myjetbrains.com`, I put `https://xxx.myjetbrains.com/youtrack`, and it worked.
