### ISSUE TITLE
YouTrack 7.0 Build 27505 - The app can't parse response

### ISSUE THREAD

**Issue by iileshii** [pbauerochse/youtrack-worklog-viewer#20]
```
00:42:04.589 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task FetchTimereport-Task changed from RUNNING to FAILED
00:42:04.589 [JavaFX Application Thread] WARN  d.p.w.fx.MainViewController - Task FetchTimereport-Task failed
00:42:04.590 [JavaFX Application Thread] WARN  d.p.w.fx.MainViewController - Showing error to user
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.StringReader@73df10a6; line: 1, column: 89] (through reference chain: de.pbauerochse.worklogviewer.youtrack.issuedetails.IssueDetailsResponse["issue"]->java.util.ArrayList[0]->de.pbauerochse.worklogviewer.youtrack.issuedetails.IssueDetails["field"]->java.util.ArrayList[0]->de.pbauerochse.worklogviewer.youtrack.issuedetails.IssueField["value"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:835) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:59) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:12) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2625) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at de.pbauerochse.worklogviewer.util.JacksonUtil.parseValue(JacksonUtil.java:23) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at de.pbauerochse.worklogviewer.youtrack.connector.YouTrackConnectorBase.fetchTaskDetails(YouTrackConnectorBase.java:231) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at de.pbauerochse.worklogviewer.fx.tasks.FetchTimereportTask.call(FetchTimereportTask.java:82) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at de.pbauerochse.worklogviewer.fx.tasks.FetchTimereportTask.call(FetchTimereportTask.java:23) ~[youtrack-worklog-viewer-2.2.2.jar:na]
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_101]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_101]
    at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_101]
00:42:09.848 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Showing log messages dialogue
00:42:09.929 [JavaFX Application Thread] DEBUG d.p.w.fx.LogViewController - Initializing
00:42:09.974 [JavaFX Application Thread] DEBUG d.p.w.fx.LogViewController - Adding WindowChangeListener
```

**Comment by pmalouin** [comment]
It is probably linked to the new "sprint" field that is returned from the API, for which the value attribute contains an array of values:

```json
	{
		"id": "WARW-12",
		"entityId": "89-89",
		"jiraId": null,
		"field": [{
			"name": "sprint",
			"value": [{
				"value": "Sprint 1",
				"id": "Alpha Board:Sprint 1"
			},
			{
				"value": "Unscheduled",
				"id": "my-work:Unscheduled"
			},
			{
				"value": "Sprint 1",
				"id": "Personnal Board:Sprint 1"
			}]
		}],
		"comment": [],
		"tag": []
	},
```

**Comment by iileshii** [comment]
#21

**Comment by pbauerochse** [comment]
Hi @iileshii,

I just merged your pull request and issued a new relase with the fix included. Thanks a lot for your work!

@pmalouin, can you confirm this issue is fixed with the new release?

Cheers

Patrick

**Comment by pmalouin** [comment]
@pbauerochse 
I confirm that the new release fixes the problem. Thanks!
