### ISSUE TITLE
Can't load token: invalid_grant (Invalid resource owner credentials)

### ISSUE THREAD

**Issue by sqrter** [pbauerochse/youtrack-worklog-viewer#23]
Does anyone use the tool with cloud youtrack version 2017.2? It started throwing error couple of weeks ago, probably after some update on the youtrack's side. Could you please help, cant even imagine how to use youtrack without this tool:(

```
10:58:59.597 [pool-2-thread-1] INFO  d.p.w.y.connector.OAuth2Connector - Fetching new access token
10:58:59.598 [pool-2-thread-1] DEBUG j.j.c.oauth2.auth.OAuth2AuthFlow - Request to: https://swupp.myjetbrains.com/hub/api/rest/oauth2/token
10:58:59.598 [pool-2-thread-1] DEBUG j.j.c.oauth2.auth.OAuth2AuthFlow - Params: {
	password: ********
	grant_type: [password]
	scope: [YouTrack]
	username: [myemail@gmail.com]
10:58:59.602 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task GetGroupByCategories-Task changed from READY to SCHEDULED
10:58:59.602 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task GetGroupByCategories-Task changed from SCHEDULED to RUNNING
10:59:04.131 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task GetGroupByCategories-Task changed from RUNNING to FAILED
10:59:04.132 [JavaFX Application Thread] WARN  d.p.w.fx.MainViewController - Task GetGroupByCategories-Task failed
10:59:04.134 [JavaFX Application Thread] WARN  d.p.w.fx.MainViewController - Showing error to user
com.intellij.hub.auth.oauth2.consumer.OAuth2TokenLoadException: Can't load token: invalid_grant (Invalid resource owner credentials)
	at jetbrains.jetpass.client.oauth2.SimpleTokenLoader.loadAccessToken(SimpleTokenLoader.java:55) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at jetbrains.jetpass.client.oauth2.token.OAuth2TokenFlow.getTokenData(OAuth2TokenFlow.java:69) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at jetbrains.jetpass.client.oauth2.token.OAuth2TokenFlow.getToken(OAuth2TokenFlow.java:46) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at de.pbauerochse.worklogviewer.youtrack.connector.OAuth2Connector.performLoginIfNecessary(OAuth2Connector.java:56) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at de.pbauerochse.worklogviewer.youtrack.connector.YouTrackConnectorBase.getLoggedInClient(YouTrackConnectorBase.java:56) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at de.pbauerochse.worklogviewer.youtrack.connector.YouTrackConnectorBase.getPossibleGroupByCategories(YouTrackConnectorBase.java:62) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at de.pbauerochse.worklogviewer.fx.tasks.GetGroupByCategoriesTask.call(GetGroupByCategoriesTask.java:27) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at de.pbauerochse.worklogviewer.fx.tasks.GetGroupByCategoriesTask.call(GetGroupByCategoriesTask.java:14) ~[youtrack-worklog-viewer-2.2.3.jar:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]
```

**Comment by pbauerochse** [comment]
Hi,

I don't have access to a cloud hosted Youtrack but from the message I would assume, that your OAuth Token is not marked as trusted or is invalid. Could you generate another token in your hub and try again with the newly generated one?

**Comment by sqrter** [comment]
Hi, thanks, I've figured it out during debugging. The problem was that I put the wrong credentials somehow :) So happy that it's not the problem with tool/api/etc.

**Comment by pbauerochse** [comment]
Glad to hear :)
